/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;
import models.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author Andrianarivony Tamby
 */
public class affichage extends javax.swing.JFrame {

    /**
     * Creates new form interfaces
     */
    public affichage() {
        initComponents();
        
        ajoutImage();
        clientaffiche();
        benefaffiche();
        //virementaffiche();
        jButton1.setForeground(new Color(255, 255, 255));
        jTextField5.getDocument().addDocumentListener(new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent e) {
        search(); // Appeler la méthode de recherche lorsque du texte est inséré
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        search(); // Appeler la méthode de recherche lorsque du texte est supprimé
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        // Ce listener est généralement utilisé pour les attributs du document, donc pas souvent nécessaire pour un JTextField
    }
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       public void ajoutImage() {
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/vues/ariary-malgache.colore.png"));
        Image image = originalIcon.getImage();
        // Redimensionner l'image à 300x300 pixels
        Image newImage = image.getScaledInstance(230, 210, java.awt.Image.SCALE_SMOOTH);
        lbllogo.setIcon(new ImageIcon(newImage));
    }
       public void benefaffiche() {
        models.MPreter total_pret = new models.MPreter();
        models.MRendre total_rendre = new models.MRendre();
        int total_benef = total_rendre.total_rendre() - total_pret.total_preter()  ;
        lblbenef.setText(""+total_benef+" Ar");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblbenef = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblvirement = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpreter = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblrendre = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        radio_apayer = new javax.swing.JRadioButton();
        radio_tout_paye = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclient = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnajoutclient = new javax.swing.JButton();
        btnactivation_clien = new javax.swing.JButton();
        btnmodifclient = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        radio_actif = new javax.swing.JRadioButton();
        radio_inactif = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setLocation(new java.awt.Point(2, 90));
        setMinimumSize(new java.awt.Dimension(1630, 850));
        setResizable(false);
        setSize(new java.awt.Dimension(1630, 850));

        jPanel1.setBackground(new java.awt.Color(45, 95, 95));
        jPanel1.setMaximumSize(new java.awt.Dimension(1630, 773));
        jPanel1.setMinimumSize(new java.awt.Dimension(1630, 773));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 850));

        jPanel2.setBackground(new java.awt.Color(45, 95, 95));

        jButton2.setBackground(new java.awt.Color(45, 95, 95));
        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(69, 169, 157));
        jButton2.setText("Clients");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setHideActionText(true);
        jButton2.setSelected(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(45, 95, 95));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(69, 169, 157));
        jButton1.setText("Benefice");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHideActionText(true);
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(45, 95, 95));
        jButton3.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton3.setForeground(new java.awt.Color(69, 169, 157));
        jButton3.setText("Virement");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setFocusable(false);
        jButton3.setHideActionText(true);
        jButton3.setSelected(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(45, 95, 95));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton4.setForeground(new java.awt.Color(69, 169, 157));
        jButton4.setText("Preter");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setFocusable(false);
        jButton4.setHideActionText(true);
        jButton4.setSelected(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(45, 95, 95));
        jButton5.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton5.setForeground(new java.awt.Color(69, 169, 157));
        jButton5.setText("Rendre");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setFocusable(false);
        jButton5.setHideActionText(true);
        jButton5.setSelected(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vues/ariary-malgache.colore.png"))); // NOI18N
        lbllogo.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vues/barreJaune.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 241, 245));
        jLabel5.setText("VolaVita Banque");
        jLabel5.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(1366, 1366, 1366))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        jTabbedPane1.setBackground(new java.awt.Color(69, 169, 157));
        jTabbedPane1.setForeground(new java.awt.Color(45, 95, 95));
        jTabbedPane1.setFocusable(false);

        jPanel3.setFocusable(false);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 95, 95));
        jLabel9.setText("BENEFICE");
        jLabel9.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 48)); // NOI18N
        jLabel1.setText("Benefice total de la Banque:");

        lblbenef.setFont(new java.awt.Font("Nirmala UI", 1, 60)); // NOI18N
        lblbenef.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(657, 657, 657)
                        .addComponent(lblbenef)))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(177, 177, 177)
                .addComponent(lblbenef)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("dashboard", jPanel3);

        jPanel5.setFocusable(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 95, 95));
        jLabel3.setText("VIREMENT");
        jLabel3.setFocusable(false);

        jButton9.setBackground(new java.awt.Color(69, 169, 157));
        jButton9.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(45, 95, 95));
        jButton9.setText("Ajouter");
        jButton9.setBorder(null);
        jButton9.setFocusable(false);
        jButton9.setName("btnajoutervirement"); // NOI18N
        jButton9.setPreferredSize(new java.awt.Dimension(240, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(69, 169, 157));
        jButton10.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(45, 95, 95));
        jButton10.setText("Suppprimer");
        jButton10.setBorder(null);
        jButton10.setFocusable(false);
        jButton10.setName("btnsupprvirement"); // NOI18N
        jButton10.setPreferredSize(new java.awt.Dimension(240, 50));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(69, 169, 157));
        jButton11.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(45, 95, 95));
        jButton11.setText("Modifier");
        jButton11.setBorder(null);
        jButton11.setFocusable(false);
        jButton11.setMaximumSize(new java.awt.Dimension(240, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(240, 50));
        jButton11.setName("btnmodifiervirement"); // NOI18N
        jButton11.setPreferredSize(new java.awt.Dimension(240, 50));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane5.setName("tableclient"); // NOI18N

        tblvirement.setBackground(new java.awt.Color(192, 223, 228));
        tblvirement.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        tblvirement.setForeground(new java.awt.Color(45, 95, 95));
        tblvirement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N Compte envoyeur", "N Compte receveur", "Montant", "Date virement"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblvirement.setFillsViewportHeight(true);
        tblvirement.setFocusCycleRoot(true);
        tblvirement.setFocusTraversalPolicyProvider(true);
        tblvirement.setFocusable(false);
        tblvirement.setGridColor(new java.awt.Color(45, 95, 95));
        tblvirement.setName("tblvirement"); // NOI18N
        tblvirement.setRowHeight(30);
        tblvirement.setSelectionBackground(new java.awt.Color(45, 95, 95));
        tblvirement.setSelectionForeground(new java.awt.Color(69, 169, 157));
        tblvirement.setSurrendersFocusOnKeystroke(true);
        jScrollPane5.setViewportView(tblvirement);
        if (tblvirement.getColumnModel().getColumnCount() > 0) {
            tblvirement.getColumnModel().getColumn(0).setResizable(false);
            tblvirement.getColumnModel().getColumn(1).setResizable(false);
            tblvirement.getColumnModel().getColumn(2).setResizable(false);
            tblvirement.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(924, 924, 924)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 516, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(343, 343, 343)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("virement", jPanel5);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(300, 64));

        tblpreter.setBackground(new java.awt.Color(192, 223, 228));
        tblpreter.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        tblpreter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N Pret", "N Compte", "Nom", "Montant Preté", "Reste a payer", "Date Pret"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpreter.setFillsViewportHeight(true);
        tblpreter.setFocusCycleRoot(true);
        tblpreter.setFocusTraversalPolicyProvider(true);
        tblpreter.setFocusable(false);
        tblpreter.setGridColor(new java.awt.Color(45, 95, 95));
        tblpreter.setIntercellSpacing(new java.awt.Dimension(4, 0));
        tblpreter.setName("tblpreter"); // NOI18N
        tblpreter.setRowHeight(30);
        tblpreter.setSelectionBackground(new java.awt.Color(49, 95, 95));
        tblpreter.setSelectionForeground(new java.awt.Color(69, 169, 157));
        tblpreter.setSurrendersFocusOnKeystroke(true);
        tblpreter.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblpreter);
        if (tblpreter.getColumnModel().getColumnCount() > 0) {
            tblpreter.getColumnModel().getColumn(0).setResizable(false);
            tblpreter.getColumnModel().getColumn(1).setResizable(false);
            tblpreter.getColumnModel().getColumn(2).setResizable(false);
            tblpreter.getColumnModel().getColumn(3).setResizable(false);
            tblpreter.getColumnModel().getColumn(4).setResizable(false);
            tblpreter.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton12.setBackground(new java.awt.Color(69, 169, 157));
        jButton12.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(45, 95, 95));
        jButton12.setText("Ajouter");
        jButton12.setBorder(null);
        jButton12.setFocusable(false);
        jButton12.setName("btnajouterpreter"); // NOI18N
        jButton12.setPreferredSize(new java.awt.Dimension(240, 50));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(69, 169, 157));
        jButton13.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(45, 95, 95));
        jButton13.setText("Rembourser");
        jButton13.setBorder(null);
        jButton13.setFocusable(false);
        jButton13.setName("btnsupprpreter"); // NOI18N
        jButton13.setPreferredSize(new java.awt.Dimension(240, 50));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(69, 169, 157));
        jButton14.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(45, 95, 95));
        jButton14.setText("Modifier");
        jButton14.setBorder(null);
        jButton14.setFocusable(false);
        jButton14.setMaximumSize(new java.awt.Dimension(240, 50));
        jButton14.setMinimumSize(new java.awt.Dimension(240, 50));
        jButton14.setName("btnmodifierpreter"); // NOI18N
        jButton14.setPreferredSize(new java.awt.Dimension(240, 50));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 95, 95));
        jLabel6.setText("PRETER");
        jLabel6.setFocusable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(20, 20, 20)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("preter", jPanel6);

        jPanel7.setFocusable(false);

        tblrendre.setBackground(new java.awt.Color(192, 223, 228));
        tblrendre.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        tblrendre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N Rendu", "N Pret", "Situation", "Reste a payer", "Date rendu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblrendre.setFillsViewportHeight(true);
        tblrendre.setFocusCycleRoot(true);
        tblrendre.setFocusTraversalPolicyProvider(true);
        tblrendre.setFocusable(false);
        tblrendre.setGridColor(new java.awt.Color(45, 95, 95));
        tblrendre.setMinimumSize(new java.awt.Dimension(60, 0));
        tblrendre.setName("tblrendre"); // NOI18N
        tblrendre.setPreferredSize(new java.awt.Dimension(525, 0));
        tblrendre.setRowHeight(30);
        tblrendre.setSelectionBackground(new java.awt.Color(45, 95, 95));
        tblrendre.setSelectionForeground(new java.awt.Color(69, 169, 157));
        tblrendre.setSurrendersFocusOnKeystroke(true);
        tblrendre.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblrendre);
        if (tblrendre.getColumnModel().getColumnCount() > 0) {
            tblrendre.getColumnModel().getColumn(0).setResizable(false);
            tblrendre.getColumnModel().getColumn(1).setResizable(false);
            tblrendre.getColumnModel().getColumn(2).setResizable(false);
            tblrendre.getColumnModel().getColumn(3).setResizable(false);
            tblrendre.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 95, 95));
        jLabel7.setText("RENDRE");
        jLabel7.setFocusable(false);

        radio_apayer.setText("Payé une part");
        radio_apayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_apayerActionPerformed(evt);
            }
        });

        radio_tout_paye.setSelected(true);
        radio_tout_paye.setText("Tout payé");
        radio_tout_paye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_tout_payeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_apayer)
                            .addComponent(radio_tout_paye))
                        .addGap(263, 263, 263))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(radio_tout_paye)
                .addGap(18, 18, 18)
                .addComponent(radio_apayer)
                .addGap(312, 312, 312)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 84, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("rendre", jPanel7);

        jPanel4.setFocusable(false);

        jScrollPane1.setName("tableclient"); // NOI18N

        tblclient.setBackground(new java.awt.Color(192, 223, 228));
        tblclient.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        tblclient.setForeground(new java.awt.Color(45, 95, 95));
        tblclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N Compte", "Nom", "Prenoms", "Tel", "Mail", "Montant", "Montant mvt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblclient.setFillsViewportHeight(true);
        tblclient.setFocusCycleRoot(true);
        tblclient.setFocusTraversalPolicyProvider(true);
        tblclient.setFocusable(false);
        tblclient.setGridColor(new java.awt.Color(45, 95, 95));
        tblclient.setName("tblclient"); // NOI18N
        tblclient.setRowHeight(30);
        tblclient.setSelectionBackground(new java.awt.Color(45, 95, 95));
        tblclient.setSelectionForeground(new java.awt.Color(69, 169, 157));
        tblclient.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblclient.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tblclient);
        if (tblclient.getColumnModel().getColumnCount() > 0) {
            tblclient.getColumnModel().getColumn(0).setResizable(false);
            tblclient.getColumnModel().getColumn(1).setResizable(false);
            tblclient.getColumnModel().getColumn(2).setResizable(false);
            tblclient.getColumnModel().getColumn(3).setResizable(false);
            tblclient.getColumnModel().getColumn(4).setResizable(false);
            tblclient.getColumnModel().getColumn(5).setResizable(false);
            tblclient.getColumnModel().getColumn(6).setResizable(false);
        }

        jTextField5.setBackground(new java.awt.Color(254, 254, 254));
        jTextField5.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(45, 95, 95)));
        jTextField5.setName("rechercherclient"); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(240, 50));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btnajoutclient.setBackground(new java.awt.Color(69, 169, 157));
        btnajoutclient.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnajoutclient.setForeground(new java.awt.Color(45, 95, 95));
        btnajoutclient.setText("Ajouter");
        btnajoutclient.setActionCommand("[69,169,157]");
        btnajoutclient.setBorder(null);
        btnajoutclient.setFocusable(false);
        btnajoutclient.setName("btnajouterclient"); // NOI18N
        btnajoutclient.setPreferredSize(new java.awt.Dimension(240, 50));
        btnajoutclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutclientActionPerformed(evt);
            }
        });

        btnactivation_clien.setBackground(new java.awt.Color(69, 169, 157));
        btnactivation_clien.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnactivation_clien.setForeground(new java.awt.Color(45, 95, 95));
        btnactivation_clien.setText("Desactiver");
        btnactivation_clien.setActionCommand("[69,169,157]");
        btnactivation_clien.setBorder(null);
        btnactivation_clien.setFocusable(false);
        btnactivation_clien.setName("btnsupprclient"); // NOI18N
        btnactivation_clien.setPreferredSize(new java.awt.Dimension(240, 50));
        btnactivation_clien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactivation_clienActionPerformed(evt);
            }
        });

        btnmodifclient.setBackground(new java.awt.Color(69, 169, 157));
        btnmodifclient.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btnmodifclient.setForeground(new java.awt.Color(45, 95, 95));
        btnmodifclient.setText("Modifier");
        btnmodifclient.setActionCommand("[69,169,157]");
        btnmodifclient.setBorder(null);
        btnmodifclient.setFocusable(false);
        btnmodifclient.setMaximumSize(new java.awt.Dimension(240, 50));
        btnmodifclient.setMinimumSize(new java.awt.Dimension(240, 50));
        btnmodifclient.setName("btnmodifierclient"); // NOI18N
        btnmodifclient.setPreferredSize(new java.awt.Dimension(240, 50));
        btnmodifclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifclientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnajoutclient, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .addComponent(btnmodifclient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnactivation_clien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnajoutclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnmodifclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnactivation_clien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 95, 95));
        jLabel8.setText("CLIENTS");
        jLabel8.setFocusable(false);

        radio_actif.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        radio_actif.setSelected(true);
        radio_actif.setText("Actif");
        radio_actif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_actifActionPerformed(evt);
            }
        });

        radio_inactif.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        radio_inactif.setText("Inactif");
        radio_inactif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_inactifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radio_actif)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radio_inactif)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_actif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio_inactif)
                .addGap(282, 282, 282)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("client", jPanel4);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//clients
    private void search() {
    String searchText = jTextField5.getText().trim();

    try {
        int red = 45; // Red component (0-255)
        int green = 95; // Green component (0-255)
        int blue = 95; // Blue component (0-255)

        JTableHeader thead = tblclient.getTableHeader();
        Color rgbColor = new Color(red, green, blue);
        Color rgbColor2 = new Color(69, 169, 157);
        thead.setBackground(rgbColor);
        thead.setFont(new Font("Nirmala UI", Font.BOLD, 22));
        thead.setForeground(rgbColor2);

        DefaultTableModel dt = (DefaultTableModel) tblclient.getModel();
        dt.setRowCount(0);

        String sql = "SELECT * FROM client WHERE (numCompte LIKE ? OR Nom LIKE ? OR Prenoms LIKE ?) AND Statut = ?";

            String statut = "oui"; // Valeur par défaut
            if (radio_actif.isSelected()) {
                statut = "oui";
            } else if (radio_inactif.isSelected()) {
                statut = "non";
            }
        try (Connection conn = models.MConnexion.SiConnectionDB();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, "%" + searchText + "%");
            stmt.setString(2, "%" + searchText + "%");
            stmt.setString(3, "%" + searchText + "%");
            stmt.setString(4, statut);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    Vector<String> v = new Vector<>();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));
                    v.add(rs.getString(7));
                    

                    dt.addRow(v);
                }
            }
        }

    } catch (Exception e) {
        e.printStackTrace(); // Affiche l'exception dans la console
    }
}
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        jButton1.setForeground(new Color(69, 169, 157));
        jButton2.setForeground(new Color(255, 255, 255));
        jButton3.setForeground(new Color(69, 169, 157));
        jButton4.setForeground(new Color(69, 169, 157));
        jButton5.setForeground(new Color(69, 169, 157));
        clientaffiche();
    }//GEN-LAST:event_jButton2ActionPerformed
//preter
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        jButton1.setForeground(new Color(69, 169, 157));
        jButton2.setForeground(new Color(69, 169, 157));
        jButton3.setForeground(new Color(69, 169, 157));
        jButton4.setForeground(new Color(255, 255, 255));
        jButton5.setForeground(new Color(69, 169, 157));
        preteraffiche();

    }//GEN-LAST:event_jButton4ActionPerformed
//dashboard
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        jButton1.setForeground(new Color(255, 255, 255));
        jButton2.setForeground(new Color(69, 169, 157));
        jButton3.setForeground(new Color(69, 169, 157));
        jButton4.setForeground(new Color(69, 169, 157));
        jButton5.setForeground(new Color(69, 169, 157));
        benefaffiche();

        //jButton2.f = Color.FromArgb(5, 38, 89);
        
    }//GEN-LAST:event_jButton1ActionPerformed
//virement
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        jButton1.setForeground(new Color(69, 169, 157));
        jButton2.setForeground(new Color(69, 169, 157));
        jButton3.setForeground(new Color(255, 255, 255));
        jButton4.setForeground(new Color(69, 169, 157));
        jButton5.setForeground(new Color(69, 169, 157));
        virementaffiche();

    }//GEN-LAST:event_jButton3ActionPerformed
//rendre
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        jButton1.setForeground(new Color(69, 169, 157));
        jButton2.setForeground(new Color(69, 169, 157));
        jButton3.setForeground(new Color(69, 169, 157));
        jButton4.setForeground(new Color(69, 169, 157));
        jButton5.setForeground(new Color(255, 255, 255));
        rendreaffiche();
        
        

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnajoutclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutclientActionPerformed
        // TODO add your handling code here:
    if(radio_inactif.isSelected())
    {
    JOptionPane.showMessageDialog(this, "Veillez activer ce compte d'abord", "Information!", JOptionPane.INFORMATION_MESSAGE);
    return;
    }
        vues.ajoutclient ajout = new vues.ajoutclient();
        ajout.show();
        clientaffiche();
    }//GEN-LAST:event_btnajoutclientActionPerformed

    private void btnmodifclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifclientActionPerformed
    if(radio_inactif.isSelected())
    {
    JOptionPane.showMessageDialog(this, "Veillez activer ce compte d'abord", "Information!", JOptionPane.INFORMATION_MESSAGE);
    return;
    }
        if(tblclient.getSelectedRowCount()>0){
            int si_nb_ligne = tblclient.getSelectedRow();
            String numcompte = (String) tblclient.getValueAt(si_nb_ligne, 0);
            String nom = (String) tblclient.getValueAt(si_nb_ligne, 1);
            String prenom = (String) tblclient.getValueAt(si_nb_ligne, 2);
            String tel = (String) tblclient.getValueAt(si_nb_ligne, 3);
            String mail = (String) tblclient.getValueAt(si_nb_ligne, 4);
            String montant = (String) tblclient.getValueAt(si_nb_ligne, 5);
           // String solde_mvt = (String) tblclient.getValueAt(si_nb_ligne, 6);
            /*txtn.setText(idproduit);
            txtlibelle.setText(libelleproduit);
            txtqteprod.setText(qtproduit);
           /* VUE.VUEPRODUIT modifModal = new VUE.VUEPRODUIT(this, "Modiffication d'un Produit : ", true, idproduit, libelleproduit, Integer.toString(qtproduit), Integer.toString(qtmvnproduit));
            modifModal.show();
            //modifModal.setVisible(true);
            jButton4.setText("ENREGISTRER");*/
            vues.ajoutclient modif = new vues.ajoutclient(numcompte,nom,prenom,tel,mail, montant);
        modif.show();
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!", "Attention!", JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodifclientActionPerformed

    private void btnactivation_clienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactivation_clienActionPerformed
        // TODO add your handling code here:
        //SUPPRIMER//////////////////////////////////////////////////////////////*//////////////////*/*////////-
          if (tblclient.getSelectedRowCount() > 0) {
        // Obtenir le numéro de compte de la ligne sélectionnée
        int si_nb_ligne = tblclient.getSelectedRow();
        String numcompte = (String) tblclient.getValueAt(si_nb_ligne, 0);
        int numcompteint = Integer.parseInt(numcompte);

        // Créer les objets de modèle pour la suppression
        models.MClient supp = new models.MClient(numcompteint);
        /*models.MPreter money_mod = new models.MPreter(numcompteint);

        // Requête SQL pour obtenir les num_pret associés au compte
        String sql = "SELECT num_pret FROM preter WHERE num_Compte = ?";
        
        try (Connection conn = models.MConnexion.SiConnectionDB();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            // Utilisation de l'entier pour le paramètre
            stmt.setInt(1, numcompteint);  
            // Demander confirmation avant suppression
            int nb = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer?", "Attention!", JOptionPane.YES_NO_OPTION);
            if (nb == JOptionPane.YES_OPTION) {
                try (ResultSet rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        int num_pret_int = rs.getInt("num_pret");
                        System.out.println("Echec de connexion à la base de données : " + num_pret_int);
                        models.MRendre suprend_cli = new models.MRendre(num_pret_int);
                        suprend_cli.supprRendreViaPret();
                    }
                }

            
                money_mod.supprPreterClient();*/
        
                
        if(btnactivation_clien.getText() == "Desactiver")
        { int nb = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment desactiver?", "Attention!", JOptionPane.YES_NO_OPTION);
            if (nb == JOptionPane.YES_OPTION)
            {
                    supp.desactivation();
            }
            
        }
        else if(btnactivation_clien.getText() == "Activer")
        { int nb = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment activer?", "Attention!", JOptionPane.YES_NO_OPTION);
            if (nb == JOptionPane.YES_OPTION)
            {
                supp.activation();
            }
            
        }
                
                clientaffiche();  // Actualiser l'affichage des clients
            
    } else {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne!", "Attention!", JOptionPane.WARNING_MESSAGE);
    } 
    }//GEN-LAST:event_btnactivation_clienActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        if(tblvirement.getSelectedRowCount()>0){
            int si_nb_ligne = tblvirement.getSelectedRow();
            String numcompte_env = (String) tblvirement.getValueAt(si_nb_ligne, 0);
            String numcompte_rec = (String) tblvirement.getValueAt(si_nb_ligne, 1);
            String montant_virement = (String) tblvirement.getValueAt(si_nb_ligne, 2);
            String datevirement = (String) tblvirement.getValueAt(si_nb_ligne, 3);
            
            /*txtn.setText(idproduit);
            txtlibelle.setText(libelleproduit);
            txtqteprod.setText(qtproduit);
           /* VUE.VUEPRODUIT modifModal = new VUE.VUEPRODUIT(this, "Modiffication d'un Produit : ", true, idproduit, libelleproduit, Integer.toString(qtproduit), Integer.toString(qtmvnproduit));
            modifModal.show();
            //modifModal.setVisible(true);
            jButton4.setText("ENREGISTRER");*/
            vues.ajoutvirement modif = new vues.ajoutvirement(numcompte_env,numcompte_rec,montant_virement,datevirement);
            modif.show();
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!", "Attention!", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //AJOUT VIREMENT
        
        vues.ajoutvirement ajout = new vues.ajoutvirement();
        ajout.show();
        virementaffiche();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //SUPPRESSION
          if(tblvirement.getSelectedRowCount()>0)
         {
                int si_nb_ligne = tblvirement.getSelectedRow();
                String numcompte_env = (String) tblvirement.getValueAt(si_nb_ligne, 0);
                String numcompte_rec = (String) tblvirement.getValueAt(si_nb_ligne, 1);
                String datetransfert = (String) tblvirement.getValueAt(si_nb_ligne, 3);
                int numcompte_env_int = Integer.parseInt(numcompte_env);
                int numcompte_rec_int = Integer.parseInt(numcompte_rec);
                models.MVirement supp = new models.MVirement(numcompte_env_int,numcompte_rec_int,datetransfert);
                int nb=0;
                nb = JOptionPane.showConfirmDialog(this, "Voulez vous annuler le virement?", "Attention!",JOptionPane.YES_NO_OPTION);
                if (nb == 0){
                    int montant_virement = supp.montantmvmt_virement();
                    
                    models.MClient vola_env = new models.MClient(numcompte_env_int);
                    models.MClient vola_rec = new models.MClient(numcompte_rec_int);
                    
                    int plus_env =  vola_env.montantmvmt()+ montant_virement ;
                    int reste_rec = vola_rec.montantmvmt()- montant_virement ;
                    
                    models.MClient modif_montant_env = new models.MClient(numcompte_env_int,plus_env);
                    models.MClient modif_montant_rec = new models.MClient(numcompte_rec_int,reste_rec);
                    modif_montant_env.modifClient_virement();
                    modif_montant_rec.modifClient_virement();
                    supp.supprVirement();
                    virementaffiche();
                } 
            
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!", "Attention!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        vues.ajoutpreter ajout = new vues.ajoutpreter();
        ajout.show();
        preteraffiche();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        //REMBOURSEMENT
         if(tblpreter.getSelectedRowCount()>0)
         {
                int si_nb_ligne = tblpreter.getSelectedRow();
                String numpret = (String) tblpreter.getValueAt(si_nb_ligne, 0);
                //String numcompte = (String) tblpreter.getValueAt(si_nb_ligne, 1);
                //String montant = (String) tblpreter.getValueAt(si_nb_ligne, 2);
                String montant_payee_str = (String) tblpreter.getValueAt(si_nb_ligne, 4);
                //int numcompte_int = Integer.parseInt(numcompte);
                int numpret_int = Integer.parseInt(numpret);
                //int montant_int = Integer.parseInt(montant);
                //models.MPreter supp = new models.MPreter(numpret_int);
                int montant_payee_int=Integer.parseInt(montant_payee_str);
                models.MRendre num_rendu = new models.MRendre(numpret_int);
               // models.MRendre situation = new models.MRendre(numpret_int);
               /*
               
               */
               
                
                
            
            vues.ajoutrendre modif = new vues.ajoutrendre(num_rendu.num_rendre(),numpret,num_rendu.situation(),montant_payee_int,num_rendu.date_rendu());
            modif.show();
                
                //(String num_rendre,String numpret_int,String situation,int montant_payee, String date_rendu)
                
                /*
                int nb=0;
                nb = JOptionPane.showConfirmDialog(this, "Voulez vous supprimer vraiment?", "Attention!",JOptionPane.YES_NO_OPTION);
                if (nb == 0){
                    
                    
                    models.MClient vola_env = new models.MClient(numcompte_int);
                    
                    
                    int plus_env =  vola_env.montantmvmt()- montant_int ;
                    
                    
                    models.MClient modif_montant_env = new models.MClient(numcompte_int,plus_env);
                    
                    modif_montant_env.modifClient_virement();
                    
                    supp.supprPreter();
                    preteraffiche();
                } */
            
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!", "Attention!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if(tblpreter.getSelectedRowCount()>0){
            int si_nb_ligne = tblpreter.getSelectedRow();
            String numpret = (String) tblpreter.getValueAt(si_nb_ligne, 0);
            String numcompte = (String) tblpreter.getValueAt(si_nb_ligne, 1);
            String montant_preter = (String) tblpreter.getValueAt(si_nb_ligne, 3);
            String datepreter = (String) tblpreter.getValueAt(si_nb_ligne, 5);
            
            /*txtn.setText(idproduit);
            txtlibelle.setText(libelleproduit);
            txtqteprod.setText(qtproduit);
           /* VUE.VUEPRODUIT modifModal = new VUE.VUEPRODUIT(this, "Modiffication d'un Produit : ", true, idproduit, libelleproduit, Integer.toString(qtproduit), Integer.toString(qtmvnproduit));
            modifModal.show();
            //modifModal.setVisible(true);
            jButton4.setText("ENREGISTRER");*/
            vues.ajoutpreter modif = new vues.ajoutpreter(numpret,numcompte,montant_preter,datepreter);
            modif.show();
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Veillez selectionner une ligne!", "Attention!", JOptionPane.WARNING_MESSAGE);
        } 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void radio_actifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_actifActionPerformed
        // TODO add your handling code here:
        
        radio_inactif.setSelected(false);
        clientaffiche();
        btnactivation_clien.setText("Desactiver");
    }//GEN-LAST:event_radio_actifActionPerformed

    private void radio_inactifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_inactifActionPerformed
        // TODO add your handling code here:
        radio_actif.setSelected(false);
        clientaffiche();
        btnactivation_clien.setText("Activer");
    }//GEN-LAST:event_radio_inactifActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void radio_tout_payeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_tout_payeActionPerformed
    radio_apayer.setSelected(false);
    rendreaffiche();        // TODO add your handling code here:
    }//GEN-LAST:event_radio_tout_payeActionPerformed

    private void radio_apayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_apayerActionPerformed
        // TODO add your handling code here:
    radio_tout_paye.setSelected(false);
    rendreaffiche();
    }//GEN-LAST:event_radio_apayerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new affichage().setVisible(true);
            }
        });
    }
    
   public void clientaffiche() {
        try {
            int red = 45; // Red component (0-255)
            int green = 95; // Green component (0-255)
            int blue = 95; // Blue component (0-255)

            JTableHeader thead = tblclient.getTableHeader();
            Color rgbColor = new Color(red, green, blue);
            Color rgbColor2 = new Color(69, 169, 157);
            Color rgbColor3 = new Color(184, 207, 229);
            Color rgbColor4 = new Color(69, 169, 157);
            thead.setBackground(rgbColor);
            thead.setFont(new Font("Nirmala UI", Font.BOLD, 22));
            thead.setForeground(rgbColor2);

            DefaultTableModel dt = (DefaultTableModel) tblclient.getModel();
            dt.setRowCount(0);

            models.MClient affichageclients = new models.MClient();
            ResultSet rsT = affichageclients.afficheClient();

            Statement s = models.MConnexion.SiConnectionDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM client WHERE Statut = 'oui'");
            if(radio_actif.isSelected()==true)
            {
             rs = s.executeQuery("SELECT * FROM client WHERE Statut = 'oui'");
             btnmodifclient.setBackground(rgbColor4);
            btnajoutclient.setBackground(rgbColor4);
            }else if(radio_inactif.isSelected()==true)
            {
            rs = s.executeQuery("SELECT * FROM client WHERE Statut = 'non'");
            btnmodifclient.setBackground(rgbColor3);
            btnajoutclient.setBackground(rgbColor3);
            }
            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));

                dt.addRow(v);
            }

            // Fermer les ressources après utilisation
            rs.close();
            s.close();

        } catch (Exception e) {
            e.printStackTrace(); // Affiche l'exception dans la console
        }
    }


    
    
    ////////////////////////////////////////////////////////virement///////////////////////////////////////////////
    
    public void virementaffiche() {
        try {
            int red = 45; // Red component (0-255)
            int green = 95; // Green component (0-255)
            int blue = 95; // Blue component (0-255)

            JTableHeader thead = tblvirement.getTableHeader();
            Color rgbColor = new Color(red, green, blue);
            Color rgbColor2 = new Color(69, 169, 157);
            thead.setBackground(rgbColor);
            thead.setFont(new Font("Nirmala UI", Font.BOLD, 22));
            thead.setForeground(rgbColor2);

            DefaultTableModel dt = (DefaultTableModel) tblvirement.getModel();
            dt.setRowCount(0);

            models.MVirement affichagevirement = new models.MVirement();
            ResultSet rsT = affichagevirement.afficheVirement();

            Statement s = models.MConnexion.SiConnectionDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM virement ORDER BY dateTransfert DESC");
            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));

                dt.addRow(v);
            }

            // Fermer les ressources après utilisation
            rs.close();
            s.close();

        } catch (Exception e) {
            System.err.println("Erreur : " + e.getMessage());
            e.printStackTrace(); // Ajouté pour afficher la trace complète de l'exception
        }
    
    }
     public void preteraffiche() 
    {
        try {
            int red = 45; // Red component (0-255)
            int green = 95; // Green component (0-255)
            int blue = 95; // Blue component (0-255)

            JTableHeader thead = tblpreter.getTableHeader();
            Color rgbColor = new Color(red, green, blue);
            Color rgbColor2 = new Color(69, 169, 157);
            thead.setBackground(rgbColor);
            thead.setFont(new Font("Nirmala UI", Font.BOLD, 22));
            thead.setForeground(rgbColor2);

            DefaultTableModel dt = (DefaultTableModel) tblpreter.getModel();
            dt.setRowCount(0);

            models.MVirement affichagevirement = new models.MVirement();
            ResultSet rsT = affichagevirement.afficheVirement();

            Statement s = models.MConnexion.SiConnectionDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM preter ORDER BY num_pret DESC");
            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                        models.MClient vola_env = new models.MClient(Integer.parseInt(rs.getString(2)));
                        String nom_complet =vola_env.nom_client()+" "+vola_env.prenom_client();
                v.add(nom_complet);
                v.add(rs.getString(3));
                        int numpret_int=Integer.parseInt(rs.getString(1));
                        models.MPreter money_mod = new models.MPreter(numpret_int);
                        //taux 10%
                        double taux = 10.0 / 100.0;
                        //total vola aloha
                        int money_int = (int) (money_mod.montantpret() * taux + money_mod.montantpret());
                        //vole efa voahefa
                        models.MRendre dejp = new models.MRendre(numpret_int);
                        int deja_payee =dejp.somme_deja_payee();

                        int reste_a_payer = money_int - deja_payee;
                v.add(Integer.toString(reste_a_payer));
                v.add(rs.getString(4));
                
                
                

                dt.addRow(v);
            }
            

            // Fermer les ressources après utilisation
            rs.close();
            s.close();

        } catch (Exception e) {
            System.err.println("Erreur : " + e.getMessage());
            e.printStackTrace(); // Ajouté pour afficher la trace complète de l'exception
        }
    
    }
     public void rendreaffiche() {
        try {
            int red = 45; // Red component (0-255)
            int green = 95; // Green component (0-255)
            int blue = 95; // Blue component (0-255)

            JTableHeader thead = tblrendre.getTableHeader();
            Color rgbColor = new Color(red, green, blue);
            Color rgbColor2 = new Color(69, 169, 157);
            thead.setBackground(rgbColor);
            thead.setFont(new Font("Nirmala UI", Font.BOLD, 22));
            thead.setForeground(rgbColor2);

            DefaultTableModel dt = (DefaultTableModel) tblrendre.getModel();
            dt.setRowCount(0);

            models.MVirement affichagevirement = new models.MVirement();
            ResultSet rsT = affichagevirement.afficheVirement();

            Statement s = models.MConnexion.SiConnectionDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM rendre ORDER BY num_rendu DESC");
            if(radio_tout_paye.isSelected()==true)
            {
             rs = s.executeQuery("SELECT * FROM rendre WHERE situation = ' Tout payé'");
             //" Tout payé");
            //cbsituation.addItem(" payé une part")
            }else if(radio_apayer.isSelected()==true)
            {
            rs = s.executeQuery("SELECT * FROM rendre WHERE situation = ' payé une part'");
            
            }
            while (rs.next()) {
                Vector<String> v = new Vector<>();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));

                dt.addRow(v);
            }

            // Fermer les ressources après utilisation
            rs.close();
            s.close();

        } catch (Exception e) {
            System.err.println("Erreur : " + e.getMessage());
            e.printStackTrace(); // Ajouté pour afficher la trace complète de l'exception
        }
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactivation_clien;
    private javax.swing.JButton btnajoutclient;
    private javax.swing.JButton btnmodifclient;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblbenef;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JRadioButton radio_actif;
    private javax.swing.JRadioButton radio_apayer;
    private javax.swing.JRadioButton radio_inactif;
    private javax.swing.JRadioButton radio_tout_paye;
    private javax.swing.JTable tblclient;
    private javax.swing.JTable tblpreter;
    private javax.swing.JTable tblrendre;
    private javax.swing.JTable tblvirement;
    // End of variables declaration//GEN-END:variables
}
