/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vues;

import static java.lang.Integer.parseInt;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Andrianarivony Tamby
 */
public class ajoutclient extends javax.swing.JFrame {
    private int montant_depart =0;
    int solde_mvt_new = 0;
    /**
     * Creates new form ajoutclient
     */
    public ajoutclient() {
        initComponents();
        lblnumcompte.setVisible(false);

    }
    public ajoutclient(String numcompte,String nom, String prenom, String tel, String mail, String montant)
    {
        initComponents();

        txtnomn.setText(nom);
        txtprenoms.setText(prenom);
        txttel.setText(tel);
        txtmail.setText(mail);
        txtmontant.setText(montant);
        //txtnomn.setText(nom);
        lblclient.setText("Modification du compte N:"+numcompte);
        btn_enregistrer_client.setText("MODIFIER");
        lblnumcompte.setVisible(false);
        lblnumcompte.setText(numcompte);
        montant_depart = Integer.parseInt(montant);


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnomn = new javax.swing.JTextField();
        txtprenoms = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtmontant = new javax.swing.JTextField();
        btn_enregistrer_client = new javax.swing.JButton();
        btn_annuler_client = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblclient = new javax.swing.JLabel();
        lblnumcompte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(190, 221, 226));
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setLocation(new java.awt.Point(1365, 223));
        setResizable(false);

        txtnomn.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtnomn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 95, 95), 1, true));
        txtnomn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtprenoms.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtprenoms.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 95, 95), 1, true));
        txtprenoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomsActionPerformed(evt);
            }
        });

        txttel.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txttel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 95, 95), 1, true));
        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });

        txtmail.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 95, 95), 1, true));

        txtmontant.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        txtmontant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(45, 95, 95), 1, true));

        btn_enregistrer_client.setBackground(new java.awt.Color(66, 173, 155));
        btn_enregistrer_client.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btn_enregistrer_client.setForeground(new java.awt.Color(45, 95, 95));
        btn_enregistrer_client.setText("Enregistrer");
        btn_enregistrer_client.setFocusable(false);
        btn_enregistrer_client.setPreferredSize(new java.awt.Dimension(200, 40));
        btn_enregistrer_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrer_clientActionPerformed(evt);
            }
        });

        btn_annuler_client.setBackground(new java.awt.Color(45, 95, 95));
        btn_annuler_client.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btn_annuler_client.setForeground(new java.awt.Color(190, 221, 226));
        btn_annuler_client.setText("Annuler");
        btn_annuler_client.setFocusable(false);
        btn_annuler_client.setPreferredSize(new java.awt.Dimension(200, 40));
        btn_annuler_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annuler_clientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 95, 95));
        jLabel1.setText("Prenoms");
        jLabel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 95, 95));
        jLabel2.setText("Nom");
        jLabel2.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 95, 95));
        jLabel3.setText("Telephone");
        jLabel3.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 95, 95));
        jLabel4.setText("E-mail");
        jLabel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 95, 95));
        jLabel5.setText("Montant");
        jLabel5.setFocusable(false);

        lblclient.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblclient.setForeground(new java.awt.Color(45, 95, 95));
        lblclient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblclient.setText("Ajout Client");
        lblclient.setFocusable(false);

        lblnumcompte.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblclient, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblnumcompte)
                                    .addGap(12, 12, 12))
                                .addComponent(txtprenoms)
                                .addComponent(txtnomn)
                                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btn_enregistrer_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_annuler_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblclient)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnomn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtprenoms, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnumcompte))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enregistrer_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_annuler_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprenomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomsActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed

    private void btn_enregistrer_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrer_clientActionPerformed
        
         try {
        // Vérifier que tous les champs sont remplis
        if (txtnomn.getText().isEmpty() || !txtnomn.getText().matches(".*[a-zA-Z0-9]+.*") || txttel.getText().isEmpty()|| !txttel.getText().matches("\\d+") || txtmail.getText().isEmpty() || txtmontant.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Remplir les champs correctement.", "Erreur de saisie", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
         String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if(!txtmail.getText().matches(emailRegex))
        {
        javax.swing.JOptionPane.showMessageDialog(this, "Email invalide", "Erreur de saisie", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Vérifier le montant
        int montant;
        try {
            montant = Integer.parseInt(txtmontant.getText());
            
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez entrer un montant valide.", "Erreur de saisie", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (montant <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Veuillez entrer un montant valide.", "Erreur de saisie", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Récupérer les données d'entrée des champs de texte
        String nom = txtnomn.getText();
        String prenoms = txtprenoms.getText();
        String tel = txttel.getText();
        String mail = txtmail.getText();

        // Créer une nouvelle instance de MClient avec les entrées fournies
        if (btn_enregistrer_client.getText().equals("MODIFIER")) {
            int numcompte = Integer.parseInt(lblnumcompte.getText());
            
            models.MClient soldemv = new models.MClient(numcompte);
            solde_mvt_new =soldemv.montantmvmt()+ montant - montant_depart;
            System.out.println(solde_mvt_new);
            if(solde_mvt_new<0)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Solde disponible sera negatif", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
            }
            models.MClient modif = new models.MClient(nom, prenoms, tel, mail, montant, solde_mvt_new,numcompte);
            modif.modifClient();
            javax.swing.JOptionPane.showMessageDialog(this, "Client modifié avec succès.", "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            String statut = "oui";
            models.MClient ajout = new models.MClient(nom, prenoms, tel, mail, montant, montant,statut);
            ajout.ajoutCLient();  // On suppose que cette méthode lance une exception en cas d'échec
            javax.swing.JOptionPane.showMessageDialog(this, "Client ajoute avec succès.", "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        // Actualiser l'affichage des clients dans l'autre interface
         try {
            vues.affichage loop = new vues.affichage();
            loop.clientaffiche(); 
            loop.revalidate();
            loop.repaint();
            System.out.println("tokony mandeh pory");
            // Actualiser la liste des clients
        } catch (Exception e) {
            System.err.println("Erreur lors de l'actualisation des clients : " + e.getMessage());
        }  // Actualiser la liste des clients

        // Fermer la fenêtre actuelle
         this.dispose();

        // Afficher un message de débogage dans la console
        System.out.println("coucou");
    } catch (Exception e) {
        // Gérer toute autre exception
        System.err.println("Erreur : " + e.getMessage());
        javax.swing.JOptionPane.showMessageDialog(this, "Une erreur est survenue lors de l'ajout du client.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_enregistrer_clientActionPerformed

    private void btn_annuler_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annuler_clientActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_annuler_clientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutclient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_annuler_client;
    private javax.swing.JButton btn_enregistrer_client;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblclient;
    private javax.swing.JLabel lblnumcompte;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmontant;
    private javax.swing.JTextField txtnomn;
    private javax.swing.JTextField txtprenoms;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    private void EXIT_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
